variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

name: $(rev:r)

steps:
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Configurations'
#   inputs:
#     PathtoPublish: conf
#     ArtifactName: 'configurations'

- task: Docker@0
  displayName: 'Build JAR File with SBT'
  inputs:
    containerregistrytype: 'Container Registry'
    action: 'Run an image'
    imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
    qualifyImageName: false
    containerName: sbt
    volumes: '$(Build.Repository.LocalPath):/app'
    containerCommand: 'sbt "set test in Test := {}" clean assembly'
    detached: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish JAR file to Artifacts'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/target/scala-2.11'
    ArtifactName: 'jar-file'

# - task: AzureCLI@2
#   displayName: 'Publish JAR file to Repo'
#   inputs:
#     azureSubscription: 'BizSpark Development (RM)'
#     scriptType: 'pscore'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az artifacts universal publish --organization https://dev.azure.com/mojio/ --feed Analytics --name com.hortonworks.hive:hive-warehouse-connector-assembly --version 1.0.0-MOJIO-$(Build.BuildNumber) --description "From Azure DevOps Build" --path $(Build.Repository.LocalPath)/target/scala-2.11

# - task: UniversalPackages@0
#   displayName: 'Publish JAR file to Repo'
#   inputs:
#     command: 'publish'
#     # "An error occurred on the service. A potentially dangerous Request.Path value was detected from the client 
#     publishDirectory: '$(Build.Repository.LocalPath)/target/scala-2.11'
#     feedsToUsePublish: 'internal'
#     vstsFeedPublish: '46ad552d-e239-4095-b661-fe4eaf9c92a4'
#     vstsFeedPackagePublish: 'com.hortonworks.hive:hive-warehouse-connector-assembly'
#     versionOption: 'custom'
#     versionPublish: '1.0.0-MOJIO-$(Build.BuildNumber)'
#     packagePublishDescription: 'From Azure DevOps Build'
#     verbosity: 'Debug'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Analytics'

- task: AzureCLI@2
  displayName: 'Publish JAR file to Repo'
  inputs:
    azureSubscription: 'BizSpark Development (RM)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # mvn deploy:deploy-file "-Durl=$(githubPackagesUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/target/scala-2.11/hive-warehouse-connector-assembly-1.0.0-MOJIO-2.jar" "-Dtoken=$(githubPackagesPassword)" "-DgeneratePom=true" "-DgeneratePom.description=mojiohiveconnector" "-Dpackaging=jar" "-Dversion=1.0.0-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.hortonworks.hive" "-DartifactId=hive-warehouse-connector-assembly"
      mvn deploy:deploy-file "-Durl=$(azDevOpsArtifactsUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/target/scala-2.11/hive-warehouse-connector-assembly-1.0.0-MOJIO-2.jar" "-Dtoken=$(azDevOpsArtifactsPassword)" "-DgeneratePom=true" "-DgeneratePom.description=mojiohiveconnector" "-Dpackaging=jar" "-Dversion=1.0.0-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.hortonworks.hive" "-DartifactId=hive-warehouse-connector-assembly"

# - task: Docker@0
#   displayName: 'Publish with SBT'
#   inputs:
#     action: 'Run an image'
#     imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
#     containerName: 'sbt'
#     volumes: '$(Build.Repository.LocalPath):/app'
#     containerCommand: 'sbt publish'
#     detached: false
#     envVars: |
#       JAVA_OPTS=-Duser=$(githubPackagesUser) -Dpassword=$(githubPackagesPassword) -Drepourl=$(githubPackagesUrl) -Drepohost=$(githubPackagesHost) -Dversion=1.0.0-MOJIO-$(Build.BuildNumber) -Dspark.version=2.3.2 -Dhadoop.version=3.1.0 -Dhive.version=3.1.0 -Dassembly.log.level=debug
# # I would have *preferred* to keep everything inside Azure DevOps, but MS has an incompatibility with SBT: https://github.com/sbt/sbt/issues/5483 and https://github.com/sbt/ivy/pull/40
# #      JAVA_OPTS=-Duser=$(azDevOpsArtifactsUser) -Dpassword=$(azDevOpsArtifactsPassword) -Drepourl=$(azDevOpsArtifactsUrl) -Drepohost=$(azDevOpsPackagesHost) -Dversion=1.0.0-MOJIO-$(Build.BuildNumber) -Dspark.version=2.3.2 -Dhadoop.version=3.1.0 -Dhive.version=3.1.0 -Dassembly.log.level=debug
