pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Configurations'
#   inputs:
#     PathtoPublish: conf
#     ArtifactName: 'configurations'

- task: Docker@0
  displayName: 'Build JAR File with SBT'
  inputs:
    containerregistrytype: 'Container Registry'
    action: 'Run an image'
    imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
    qualifyImageName: false
    containerName: sbt
    volumes: '$(Build.Repository.LocalPath):/app'
    containerCommand: 'sbt "set test in Test := {}" clean assembly'
    detached: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish JAR file'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/target/scala-2.11'
    ArtifactName: 'jar-file'

- task: Docker@0
  displayName: 'Publish with SBT'
  inputs:
    action: 'Run an image'
    imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
    containerName: 'sbt'
    volumes: '$(Build.Repository.LocalPath):/app'
    containerCommand: 'sbt publish -Duser=$(repoUser) -Dpassword=$(repoPassword) -Drepourl=$(repoUrl) -Dversion=1.0.0-MOJIO-$(Build.BuildNumber) -Dspark.version=2.3.2 -Dhadoop.version=3.1.0 -Dhive.version=3.1.0 -Dassembly.log.level=debug'
    detached: false
    # envVars: |
    #   user=$(repoUser)
    #   password=$(repoPassword)
    #   repourl=$(repoUrl)
    #   version=1.0.0-MOJIO-$(Build.BuildNumber)
    #   spark.version=2.3.2
    #   hadoop.version=3.1.0
    #   hive.version=3.1.0
    #   assembly.log.level=debug
